---
- name: Check if CXS is installed
  stat:
    path: /usr/sbin/cxs
  register: cxs_check
  changed_when: false
  check_mode: no
  tags: always

- name: Create cxs_installed variable.
  set_fact:
    cxs_installed: "{{ cxs_check.stat.exists|bool }}"
  check_mode: no
  tags: always

- name: Include the CXS Installer Task
  include_tasks: install.yml
  when: cxs_installed != true and (install_cxs is defined and install_cxs == 'true')
