---
- name: Check if CMQ is installed
  stat:
    path: /usr/local/cpanel/whostmgr/docroot/cgi/configserver/cmq/cmq.conf
  register: cmq_check
  changed_when: false
  check_mode: no
  tags: always

- name: Create cmq_installed variable.
  set_fact:
    cmq_installed: "{{ cmq_check.stat.exists|bool }}"
  check_mode: no
  tags: always

- name: Include the CMQ Installer Task
  include_tasks: install.yml
  when: cmq_installed != true and (install_cmq is defined and install_cmq == 'true')
